# Generated by Django 5.1.4 on 2024-12-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorstatistic',
            name='stat_type',
            field=models.CharField(choices=[('Download CV', 'Download CV'), ('Contact', 'Contact'), ('Visit', 'Visit')], max_length=50),
        ),
    ]
