# Generated by Django 5.1.4 on 2024-12-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_visitorstatistic_stat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects/'),
        ),
    ]
