services:
  - type: web
    name: -portfolio
    env: docker
    plan: free
    region: asia-southeast1
    dockerfilePath: ./Dockerfile
    # envVars:
      # - fromGroup: saran-portfolio-env  # 👈 You’ll create this in Render dashboard
