FONT_AWESOME_ICONS = [
    # Programming Languages
    ("fab fa-html5", "HTML5"),
    ("fab fa-css3-alt", "CSS3"),
    ("fab fa-js", "JavaScript"),
    ("fab fa-python", "Python"),
    ("fab fa-java", "Java"),
    ("fab fa-php", "PHP"),
    ("fas fa-code", "C++"),
    ("fas fa-database", "SQL"),
    ("fab fa-swift", "Swift"),

    
    # Tools and Frameworks
    ("fab fa-git-alt", "Git"),
    ("fab fa-github", "GitHub"),
    ("fab fa-docker", "Docker"),
    ("fas fa-cloud", "Cloud"),
    ("fab fa-aws", "AWS"),
    ("fab fa-linux", "Linux"),
    ("fab fa-windows", "Windows"),
    ("fab fa-android", "Android"),
    ("fab fa-apple", "iOS"),
    ("fab fa-bootstrap", "Bootstrap"),
    ("fab fa-react", "React"),
    ("fab fa-angular", "Angular"),
    ("fab fa-node-js", "Node.js"),
    ("fab fa-laravel", "Laravel"),
    ("fab fa-vuejs", "Vue.js"),
    ("fab fa-wordpress", "WordPress"),
    ("fab fa-joomla", "Joomla"),
    ("fab fa-npm", "npm"),
    ("fab fa-yarn", "Yarn"),
    ("fab fa-sass", "Sass"),
    ("fab fa-less", "Less"),
    ("fab fa-gulp", "Gulp"),
    ("fab fa-grunt", "Grunt"),
    ("fab fa-webpack", "Webpack"),
    ("fab fa-figma", "Figma"),
    ("fab fa-adobe", "Adobe XD"),
    ("fab fa-sketch", "Sketch"),
    
    # Firmware and IoT
    ("fas fa-microchip", "Firmware"),
    ("fas fa-satellite-dish", "IoT Devices"),
    ("fas fa-cogs", "Embedded Systems"),
    ("fas fa-robot", "Robotics"),
    ("fas fa-wifi", "Sensors"),
    ("fas fa-project-diagram", "Automation"),
    
    # General Skills
    ("fas fa-chart-line", "Data Analysis"),
    ("fas fa-robot", "Machine Learning"),
    ("fas fa-shield-alt", "Cybersecurity"),
    ("fas fa-vial", "Software Testing"),
    ("fas fa-tools", "DevOps"),
    ("fas fa-network-wired", "Networking"),
    ("fas fa-link", "Blockchain"),
    ("fas fa-robot", "Artificial Intelligence"),
    ("fas fa-robot", "Natural Language Processing"),
    ("fas fa-robot", "Computer Vision"),
    ("fas fa-robot", "Deep Learning"),
    ("fas fa-robot", "Neural Networks"),
    ("fas fa-robot", "Reinforcement Learning"),
    ("fas fa-robot", "Supervised Learning"),
    ("fas fa-robot", "Unsupervised Learning"),
    ("fas fa-robot", "Semi-supervised Learning"),
    ("fas fa-robot", "Transfer Learning"),
    ("fas fa-robot", "Generative Adversarial Networks"),
    ("fas fa-robot", "Convolutional Neural Networks"),
    ("fas fa-robot", "Recurrent Neural Networks"),
    ("fas fa-robot", "Long Short-Term Memory"),
    ("fas fa-robot", "Gated Recurrent Unit"),
    ("fas fa-robot", "Bidirectional Recurrent Neural Networks"),
    ("fas fa-robot", "Transformer Networks"),
    ("fas fa-robot", "BERT"),
    ("fas fa-robot", "GPT-3"),
    ("fas fa-robot", "Deep Reinforcement Learning"),
    ("fas fa-robot", "Q-Learning"),
    ("fas fa-robot", "Deep Q-Learning"),
    ("fas fa-robot", "Policy Gradient Methods"),
    ("fas fa-robot", "Actor-Critic Methods"),
    ("fas fa-robot", "Proximal Policy Optimization"),
    ("fas fa-robot", "Deep Deterministic Policy Gradient"),
    ("fas fa-robot", "Twin Delayed Deep Deterministic Policy Gradient"),
    ("fas fa-robot", "Soft Actor-Critic"),
    ("fas fa-robot", "Model-Based Reinforcement Learning"),
    ("fas fa-robot", "Model-Free Reinforcement Learning"),
    ("fas fa-robot", "Imitation Learning"),
    ("fas fa-robot", "Meta-Learning"),
    ("fas fa-robot", "Multi-Agent Reinforcement Learning"),
    ("fas fa-robot", "Multi-Task Learning"),
    ("fas fa-robot", "Transfer Learning"),
    ("fas fa-robot", "Zero-Shot Learning"),
    ("fas fa-robot", "Few-Shot Learning"),
    ("fas fa-robot", "One-Shot Learning"),
    ("fas fa-robot", "Self-Supervised Learning"),
    ("fas fa-robot", "Semi-Supervised Learning"),
    ("fas fa-robot", "Unsupervised Learning"),
    ("fas fa-robot", "Self-Attention Mechanism"),
    ("fas fa-robot", "Attention Mechanism"),
    ("fas fa-robot", "Transformer Networks"),
    ("fas fa-robot", "BERT"),
    ("fas fa-robot", "GPT-3"),
    ("fas fa-robot", "Deep Learning Frameworks"),
    ("fas fa-robot", "TensorFlow"),
    ("fas fa-robot", "Keras"),
    ("fas fa-robot", "PyTorch"),
    ("fas fa-robot", "MXNet"),
    ("fas fa-robot", "Theano"),
    ("fas fa-robot", "Deep Learning Libraries"),
    ("fas fa-robot", "NumPy"),
    ("fas fa-robot", "Pandas"),
    ("fas fa-robot", "Matplotlib"),
    ("fas fa-robot", "Seaborn"),
    ("fas fa-robot", "Scikit-Learn"),
    ("fas fa-robot", "NLTK"),
    ("fas fa-robot", "SpaCy"),
    ("fas fa-robot", "Gensim"),
    ("fas fa-robot", "OpenCV"),
    ("fas fa-robot", "Scrapy"),
    ("fas fa-robot", "Beautiful Soup"),
    ("fas fa-robot", "TensorFlow"),
    ("fas fa-robot", "Keras"),
    ("fas fa-robot", "PyTorch"),
    ("fas fa-robot", "MXNet"),
    ("fas fa-robot", "Theano"),
    ("fas fa-robot", "Deep Learning Libraries"),
    ("fas fa-robot", "NumPy"),
    ("fas fa-robot", "Pandas"),
    ("fas fa-robot", "Matplotlib"),
    ("fas fa-robot", "Seaborn"),
    ("fas fa-robot", "Scikit-Learn"),
    ("fas fa-robot", "NLTK"),
    ("fas fa-robot", "SpaCy"),
    ("fas fa-robot", "Gensim"),
    ("fas fa-robot", "OpenCV"),
    ("fas fa-robot", "Scrapy"),
    ("fas fa-robot", "Beautiful Soup"),
    ("fas fa-robot", "Deep Learning Frameworks"),
    ("fas fa-robot", "TensorFlow"),
    ("fas fa-robot", "Keras"),
    ("fas fa-robot", "PyTorch"),
    ("fas fa-robot", "MXNet"),
    ("fas fa-robot", "Theano"),
    ("fas fa-robot", "Deep Learning Libraries"),
    ("fas fa-robot", "NumPy"),
    ("fas fa-robot", "Pandas"),
    ("fas fa-robot", "Matplotlib"),
    ("fas fa-robot", "Seaborn"),
    ("fas fa-robot", "Scikit-Learn"),
    ("fas fa-robot", "NLTK"),
    ("fas fa-robot", "SpaCy"),
    ("fas fa-robot", "Gensim"),
    ("fas fa-robot", "OpenCV"),
    ("fas fa-robot", "Scrapy"),
    ("fas fa-robot", "Beautiful Soup"),
    ("fas fa-robot", "Deep Learning Frameworks"),
    ("fas fa-robot", "TensorFlow"),
    ("fas fa-robot", "Keras"),
    
    # Common Icon
    ("fas fa-certificate", "Default Skill"),

    # Add more icons here
]
