# Generated by Django 5.1.4 on 2024-12-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='fas fa-star', max_length=50),
        ),
    ]
