# Generated by Django 5.1.4 on 2025-01-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_skill_type_alter_skill_icon_alter_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
