# Generated by Django 5.1.4 on 2025-01-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_profile_github_link_profile_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recipient_email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
    ]
