# Generated by Django 5.1.4 on 2025-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_profile_recipient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_clicks', models.PositiveIntegerField(default=0)),
                ('github_clicks', models.PositiveIntegerField(default=0)),
                ('cv_downloads', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
