# Generated by Django 5.1.4 on 2025-01-03 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='cv_downloads',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='github_clicks',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='linkedin_clicks',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='messages_sent',
        ),
        migrations.AddField(
            model_name='metrics',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metrics',
            name='event_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='metrics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
