# Generated by Django 5.1.4 on 2025-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_remove_metrics_cv_downloads_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrics',
            options={'verbose_name_plural': 'Metrics'},
        ),
        migrations.AlterField(
            model_name='metrics',
            name='event_type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn Click'), ('github', 'GitHub Click'), ('cv', 'CV Download'), ('message', 'Message Sent')], max_length=50),
        ),
    ]
