# Generated by Django 5.1.4 on 2025-01-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_metrics_options_alter_metrics_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrics',
            options={'verbose_name': 'Metric', 'verbose_name_plural': 'Metrics'},
        ),
        migrations.AlterField(
            model_name='metrics',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
