# Generated by Django 5.1.4 on 2025-01-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_metrics_options_alter_metrics_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrics',
            options={},
        ),
    ]
