# Generated by Django 5.1.6 on 2025-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_alter_metrics_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Softskills', 'Softskills'), ('Tools', 'Tools')], default='Tools', max_length=50),
        ),
    ]
