# Generated by Django 5.1.6 on 2025-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_alter_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_quote',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
