# Generated by Django 5.1.6 on 2025-05-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_profile_about_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
