# Generated by Django 5.1.6 on 2025-05-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_profile_loation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='loation',
            new_name='location',
        ),
    ]
