# Generated by Django 5.1.6 on 2025-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_rename_loation_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typewriter',
            field=models.CharField(default='', max_length=100),
        ),
    ]
