# Generated by Django 5.1.6 on 2025-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_profile_typewriter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
