# Generated by Django 5.1.6 on 2025-05-24 19:48

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_profile_twitter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='month',
            field=models.PositiveSmallIntegerField(default=about.models.Metrics.get_current_month, editable=False),
        ),
        migrations.AddField(
            model_name='metrics',
            name='year',
            field=models.PositiveSmallIntegerField(default=about.models.Metrics.get_current_year, editable=False),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='event_type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn Click'), ('github', 'GitHub Click'), ('cv', 'CV Download'), ('message', 'Message Sent'), ('website_view', 'Website View')], max_length=50),
        ),
    ]
