# Generated by Django 5.1.6 on 2025-05-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_metrics_month_metrics_year_alter_metrics_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrics',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Metrics'},
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='month',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='year',
        ),
        migrations.AddField(
            model_name='metrics',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('linkedin', 'LinkedIn Click'), ('github', 'GitHub Click'), ('twitter', 'Twitter Click'), ('download_cv', 'CV Download'), ('send_message', 'Message Sent')], max_length=20),
        ),
    ]
