# Generated by Django 5.1.6 on 2025-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_alter_metrics_options_remove_metrics_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='referrer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
