# Generated by Django 5.1.6 on 2025-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_metrics_path_metrics_referrer_metrics_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('linkedin', 'LinkedIn Click'), ('github', 'GitHub Click'), ('twitter', 'Twitter Click'), ('download_cv', 'CV Download'), ('contact_form_submission', 'Contact Form Submission')], max_length=30),
        ),
    ]
