# Generated by Django 5.1.6 on 2025-05-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_alter_metrics_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favicon_icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_name',
            field=models.CharField(default='My Portfolio', max_length=100),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('linkedin', 'LinkedIn Click'), ('github', 'GitHub Click'), ('twitter', 'Twitter Click'), ('download_cv', 'CV Download'), ('send_message', 'Message Sent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Softskills', 'Softskills'), ('Tools', 'Tools'), ('Database', 'Database')], default='Tools', max_length=50),
        ),
    ]
