# Generated by Django 5.1.6 on 2025-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0023_profile_favicon_icon_profile_title_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
