# Generated by Django 5.1.6 on 2025-06-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0024_metrics_month_metrics_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('linkedin', 'LinkedIn Click'), ('github', 'GitHub Click'), ('twitter', 'Twitter Click'), ('download_cv', 'CV Download'), ('send_message', 'Message Sent')], max_length=500),
        ),
    ]
