# Generated by Django 5.1.6 on 2025-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0026_alter_profile_cv_alter_profile_favicon_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Softskills', 'Softskills'), ('Tools', 'Tools'), ('Database', 'Database')], default='Tools', max_length=50),
        ),
    ]
