# Generated by Django 5.1.6 on 2025-06-02 19:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0027_alter_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/og/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='og_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
